server:
  port: 80
#  servlet:
#    context-parameters: # 启动初始化参数s
#      teacher: Emma


spring:
  messages:
    basename: i18n/Message
  servlet:
    multipart:
      enabled: true # 启用上传文件支持，其默认为 true
      max-file-size: 100MB # 单次上传的最大长度
      max-request-size: 200MB # 每次请求允许上传的最大长度
      file-size-threshold: 1MB # 每次达到1MB时写入磁盘
      location: / # 临时存储目录
  mail:
    host: smtp.exmail.qq.com # 一定使用合法的SMTP
    username: system@aigs.ltd
    password: 4FhLnzR5p7EU8uSm
    properties:
      smtp:
      #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
      #        debug: true
      mail.smtp.auth: true # 启用SMTP认证
      mail.smtp.starttls.enabled: true  # 启用SMTP认证
      mail.smtp.starttls.required: true # 必须采用加密链接
      mail.smtp.ssl.enabled: true
    default-encoding: utf-8
    port: 465
    test-connection: false
    protocol: smtps
  datasource:
    url: jdbc:mysql://www.tqy.pub:3306/car_sale
    username: car_sale
    password: MjfaamhZpyhX7DrA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
#  server:
#    port: 9090
#  endpoint:
#    health:
#      show-details: always  # 显示异常信息
#      show-components: always # 显示组件信息
#    shutdown:
#      enabled: true # 允许远程关闭
#  endpoints:
#    web:
#      exposure:
#        include: "*" # 开启所有监控
logging:
  level: # 需要配置一个Map集合
    root: info # 基本的日志级别
    com.demo.action.MessageAction: warn # 针对开发包的日志级别
#  file:
#    path: aigs-logs # 日志保存的路径
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger] %msg%n" # 文件日志格式
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger] %msg%n" # 控制台日志格式
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# Actuator 配置项
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"  # 开放全部的微服务监控端口
      base-path: /actuator  # 监控服务的父路径

