source:
  deptno: 10
  dname: 教学研发部
  company:
    cid: 1009
    cname: 科技教育
  emps:
    - emp:
      empno: 7312
      ename: Emma
      job: 办事员
    - emp:
      empno: 1234
      ename: Allis
      job: 教学主任
    - emp:
      empno: 5931
      ename: Smith
      job: 董事长