server:
  port: 80
  servlet:
    context-parameters:
      teacher: Emma

spring:
  messages:
    basename: i18n/Message
  servlet:
    multipart:
      enabled: true # 启用上传文件支持，其默认为 true
      max-file-size: 100MB # 单次上传的最大长度
      max-request-size: 200MB # 每次请求允许上传的最大长度
      file-size-threshold: 1MB # 每次达到1MB时写入磁盘
      location: / # 临时存储目录
  mail:
    host: smtp.exmail.qq.com # 一定使用合法的SMTP
    username: system@aigs.ltd
    password: 4FhLnzR5p7EU8uSm
    properties:
      smtp:
      #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
      #        debug: true
      mail.smtp.auth: true # 启用SMTP认证
      mail.smtp.starttls.enabled: true  # 启用SMTP认证
      mail.smtp.starttls.required: true # 必须采用加密链接
      mail.smtp.ssl.enabled: true
    default-encoding: utf-8
    port: 465
    test-connection: false
    protocol: smtps

